Add ability to specify parameters on channel creation
RogueException/Discord.Net pull request #1020
Opened 2018-04-06 07:47 UTC by Joe4evr

Proposing this solution for #1019.

I'm not 100% sure if this'll Just Work™, so please tell me if more needs to be done.

2018-04-06 09:08 UTC, JaydenMaalouf commented
I can't wait to try this!

2018-04-06 09:35 UTC, Still34 commented
I'm not sure if I agree with the `Func` approach. Doesn't seem to fit the style.

2018-04-06 09:43 UTC, Joe4evr commented
It's literally the same thing we do for `ModifyAsync()`.

2018-04-06 12:47 UTC, AntiTcb requested changes

2018-04-06 12:47 UTC, AntiTcb commented on src/Discord.Net.Core/Entities/Guilds/IGuild.cs
> +        Task<ITextChannel> CreateTextChannelAsync(string name, RequestOptions options = null, Action<TextChannelProperties> func = null);
I really don't think having the action being the last parameter is worth avoiding making a breaking change. Just way too inconsistent.

2018-04-06 12:47 UTC, AntiTcb commented on src/Discord.Net.Rest/API/Rest/CreateGuildChannelParams.cs
>          public ChannelType Type { get; }
This field's actually optional. 
<https://discordapp.com/developers/docs/resources/guild#create-guild-channel>
>All parameters for this endpoint are optional excluding `name`

2018-04-06 13:06 UTC, Joe4evr commented on src/Discord.Net.Rest/API/Rest/CreateGuildChannelParams.cs
>          public ChannelType Type { get; }
I left that how I found it.

2018-04-17 11:16 UTC, JaydenMaalouf approved these changes
Can confirm this works! Channels (both text and voice alike) are now created within their desired categories, with their desired parameters.

2018-05-17 14:21 UTC, FiniteReality commented
@Joe4evr Is this PR still alive?

2018-05-24 23:55 UTC, closed without merging