TimeSpan parser
RogueException/Discord.Net pull request #1131
Opened 2018-08-22 20:19 UTC by ericmck2000

This change will greatly increase the success rate for the TimeSpan parser to actually work, by leveraging the built-in TimeSpan.Parse, with no additional parameters.

2018-08-22 20:20 UTC, XtremeOwnageDotCom commented
Related Issues:

https://github.com/RogueException/Discord.Net/issues/817

2018-08-22 20:26 UTC, FiniteReality requested changes

2018-08-22 20:26 UTC, FiniteReality commented on src/Discord.Net.Commands/Readers/TimeSpanTypeReader.cs
> +            else if (TimeSpan.TryParse(data, out TimeSpan Time))
Use `out var time` instead

2018-08-22 20:37 UTC, ericmck2000 commented on src/Discord.Net.Commands/Readers/TimeSpanTypeReader.cs
> +            else if (TimeSpan.TryParse(data, out TimeSpan Time))
Updated.

2018-08-23 14:25 UTC, k-boyle commented on src/Discord.Net.Commands/Readers/TimeSpanTypeReader.cs
> +            else if (TimeSpan.TryParse(data, out var time))
Forgive me if I'm wrong, but couldn't you just do, `out timeSpan` because of the previous `out`?

2018-08-23 14:42 UTC, ericmck2000 commented on src/Discord.Net.Commands/Readers/TimeSpanTypeReader.cs
> +            else if (TimeSpan.TryParse(data, out var time))
You are absolutely correct. I didn't think about it. Updated.

2018-08-29 16:40 UTC, FiniteReality commented
I've had more thought about this, and I think it would be better in the long term to add additional formats to the `_formats` array. For example, TimeSpan.TryParse uses this format string: `[ws][-]{ d | d.hh:mm[:ss[.ff]] | hh:mm[:ss[.ff]] }[ws]`, which we could easily replicate if we wrote a parser ourselves.
In the long term, I think a span-based typereader for reading dates and times would actually be superior to using TimeSpan.TryParse or TryParseExact

2018-08-29 16:54 UTC, ericmck2000 commented
As another method, There is an issue over at Humanizer to basically De-Humanize a string into a timespan too.

https://github.com/Humanizr/Humanizer/issues/691

If that issue gets traction, can piggy-back the efforts.

2019-01-03 15:30 UTC, ericmck2000 commented
Closing this.

2019-01-03 15:30 UTC, closed without merging