Add Add Guild Member Endpoint
RogueException/Discord.Net pull request #1183
Opened 2018-10-25 14:53 UTC by AntiTcb

Could use some assistance with testing this one if anyone already has an Oauth workflow setup.

Nitpick for later, we should probably revise our naming scheme for GuildUser to be GuildMember in all cases to be consistent with Discord.

2018-10-25 16:11 UTC, Chris-Johnston approved these changes
After testing with the following steps, these changes work for me:

1. Use the OAuth2 URL generator on a bot application, with the `guilds.join` scope.
2. POST the code in the querystring, [as defined in steps here](https://discordapp.com/developers/docs/topics/oauth2#authorization-code-grant)
3. Have a test bot create a new guild, then call `AddGuildUserAsync` with the token from step 2. `AddGuildUserProperties` properties all appear to work as expected\*, including roles.

~~\*I'm not sure if Deafen/Mute should do anything if that's a client-side feature? Toggling these values didn't appear to make a difference.~~ EDIT: These work as expected, and can be seen when actually joining a voice channel, and not from the corner of the client.

2018-10-27 15:59 UTC, AntiTcb commented
It's not necessary on the library's end to catch that. The client's the one that should handle that case.

2018-10-29 16:33 UTC, Chris-Johnston requested changes

2018-10-29 16:33 UTC, Chris-Johnston commented on src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs
> +                var ids = args.Roles.Value.Select(r => r.Id);
`ids` isn't used here?

2018-10-29 16:50 UTC, Chris-Johnston approved these changes

2018-11-05 23:34 UTC, merged