(Part 3 of 4) Solves UdpClient "ObjectDisposedException"
RogueException/Discord.Net pull request #1202
Opened 2018-11-28 00:42 UTC by ComputerMaster1st

Hi There,

Please refer to https://github.com/RogueException/Discord.Net/pull/1095#issuecomment-400067303 for details on this commit.

Tested & Non-Breaking.

Regards,

CM1

2018-11-28 00:55 UTC, AntiTcb requested changes

2018-11-28 00:55 UTC, AntiTcb commented on src/Discord.Net.WebSocket/Net/DefaultUdpSocket.cs
> +                _ = receiveTask.ContinueWith((recieveResult) =>
Fix the spelling of `receiveResult`.

2018-11-28 00:59 UTC, ComputerMaster1st commented on src/Discord.Net.WebSocket/Net/DefaultUdpSocket.cs
> +                _ = receiveTask.ContinueWith((recieveResult) =>
Fixed.

2018-11-29 01:56 UTC, AntiTcb commented on src/Discord.Net.WebSocket/Net/DefaultUdpSocket.cs
> +                _ = receiveTask.ContinueWith((recieveResult) =>
The variable is still misspelled.

2018-11-29 10:13 UTC, ComputerMaster1st commented on src/Discord.Net.WebSocket/Net/DefaultUdpSocket.cs
> +                _ = receiveTask.ContinueWith((recieveResult) =>
Done.

2018-11-29 22:20 UTC, merged