Fix #1233, Add properties missing from User and Activity models
RogueException/Discord.Net pull request #1237
Opened 2019-01-12 18:47 UTC by Chris-Johnston

Fix #1233 

This PR adds some properties that were missing from the API models, and implements them in the Socket and Rest types.

**Activity:**
- Adds the Activity `Flags` property. This determines which actions a user can take (join a game, watch a stream, listen along)
   - Added the ActivityFlag enum for each of these flags, and an extension method for IActivity to check the state of these flags

**User:**
- Adds the User `Flags` property. This determines some properties about a user (hypesquad, early nitro adopter, staff)
  - Adds the UserFlag type. Some of these flags are not in the official documentation, and were determined with client developer tools.
  - Adds an extension method for checking if these flags are applied
- Adds the `PremiumType` property and enum, which is the subscription that is active for a user's account.
- Adds the `Locale` property, which is the user's selected locale.

I encountered some difficulty testing that the following properties:
- `User#Flags`, I don't have any flags on my account, nor do I have my debugging bot in a guild with a user that has flags
- `User#PremiumType` This value may require oauth scopes, I only get null values.
- `User#Locale` This value may require oauth scopes, I only get null values.

2019-01-12 23:28 UTC, Joe4evr reviewed
This might be overly nit-picky, but I'm practicing doing code review, as I suspect I'm gonna do a lot of it in the near future.

2019-01-12 23:28 UTC, Joe4evr commented on src/Discord.Net.Core/Entities/Activities/ActivityFlag.cs
> +    public enum ActivityFlag
A flags enum is [recommended to be named in plural and without `Flag`/`Flags` suffix](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#naming-enumerations).

2019-01-12 23:28 UTC, Joe4evr commented on src/Discord.Net.Core/Entities/Users/UserFlag.cs
> +    public enum UserFlag
Ditto on the enum naming.

2019-01-12 23:28 UTC, Joe4evr commented on src/Discord.Net.Core/Entities/Users/IUser.cs
> +        ///     The type of Nitro subscription the user subscribes to, or null if this value could not be determined.
@Still34 Don't we always want language keywords (like `null`) highlighted in the docs? Need to know if this needs changing for consistency.

2019-01-12 23:28 UTC, Joe4evr commented on src/Discord.Net.Core/Entities/Activities/ActivityFlag.cs
> +        JoinRequest = 0b1000,
Missing doc comment.

2019-01-12 23:28 UTC, Joe4evr commented on src/Discord.Net.Core/Entities/Users/PremiumType.cs
> +        None = 0,
Missing doc comment.

2019-01-12 23:28 UTC, Joe4evr commented on src/Discord.Net.Core/Entities/Users/UserFlag.cs
> +        HypeSquadEvents = 0b100,
Missing doc comment.

2019-01-12 23:28 UTC, Joe4evr commented on src/Discord.Net.Core/Entities/Activities/ActivityFlag.cs
> +        Instance = 1,
Missing doc comment and a 0 value.

2019-01-12 23:55 UTC, Chris-Johnston commented
Not nit-picky at all, I appreciate the detailed review.

2019-01-12 23:56 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Users/IUser.cs
> +        ///     The type of Nitro subscription the user subscribes to, or null if this value could not be determined.
iirc for language keywords like `null` we use `<c>null</c>`

2019-01-13 00:07 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Activities/ActivityFlag.cs
> +        JoinRequest = 0b1000,
I was a bit unsure about when this flag is used, I think it's used whenever there's an "Ask to join" button on an activity?

2019-01-13 00:37 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Activities/ActivityFlag.cs
> +        Instance = 1,
Added a 0 value. Wasn't sure what this flag is used for, so I'm not sure what to write in xmldocs.

2019-01-13 00:44 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Users/UserFlag.cs
> +        HypeSquadEvents = 0b100,
Here also I was unsure about where this is used. I think this may have been the old hypesquad flag, before they introduced the houses?

2019-01-13 00:46 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Activities/ActivityFlag.cs
> +    public enum ActivityFlag
[I was unsure if we should stray from the name used by the Discord API docs](https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-flags). I guess `ActivityProperties` and `UserProperties` might be alright alternatives?

2019-01-13 04:31 UTC, Still34 commented on src/Discord.Net.Core/Entities/Users/IUser.cs
> +        ///     The type of Nitro subscription the user subscribes to, or null if this value could not be determined.
Yes, we do. We use <c> tag to wrap out null.

2019-01-13 05:54 UTC, Still34 requested changes

2019-01-13 05:54 UTC, Still34 commented on src/Discord.Net.Core/Entities/Activities/IActivity.cs
> +        ///     The flags that are relevant to this activity.
Verb is required, i.e. `Gets....`

2019-01-13 05:54 UTC, Still34 commented on src/Discord.Net.Core/Entities/Users/IUser.cs
> +        ///     The flags that are applied to a user's account.
Ditto with summary verb.

2019-01-13 05:54 UTC, Still34 commented on src/Discord.Net.Core/Entities/Users/IUser.cs
> +        ///     The type of Nitro subscription that is active on this user's account.
Ditto with summary verb.

2019-01-13 05:54 UTC, Still34 commented on src/Discord.Net.Core/Entities/Users/IUser.cs
> +        ///     The user's chosen language option.
Ditto with summary verb.

2019-01-13 05:54 UTC, Still34 commented on src/Discord.Net.Core/Entities/Users/IUser.cs
> +        /// </returns>
An example of the returned value would be preferred, since a `string` type is rather generic.

2019-01-27 05:50 UTC, Still34 commented
It doesn't look like the `Details` field is being exposed into the public `Game` model?

2019-01-27 08:11 UTC, Chris-Johnston commented
Odd, so after some looking `Details` is currently used to populate the `TrackTitle` property of `SpotifyGame`.

2019-01-30 04:11 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Users/UserFlag.cs
> +        HypeSquadEvents = 0b100,
I removed this flag in 802d489f474e5e0b0f4e0a9cc95cdba354df4363 , as it seems that this flag has been replaced with the new HypeSquad flags.

2019-06-12 20:00 UTC, merged