Cumulative Documentation Updates
RogueException/Discord.Net pull request #1437
Opened 2020-01-07 08:24 UTC by Still34

# Summary

This is part of the cumulative documentation update featured in the nightly version of the documentation seen on https://docs.stillu.cc.

# What's new?

* Target .NET Standard 2.0 per d199d93ae42120d36c5d856f0664efb61b7fb1a7 for documentation generation
* Update copyright year and package version
* Update `CommandService.CommandExecuted` summary per e8cb03170476bd4b20a18cfff1f3784783649c80
* Fix various invalid crefs
* Fix example text rendering (used to be rendered as code blocks)
+ Add named argument guide by @Joe4evr

2020-01-07 11:36 UTC, Joe4evr approved these changes

2020-01-16 09:28 UTC, Chris-Johnston requested changes
Overall this looks good, I just had a few wording suggestions.

2020-01-16 09:28 UTC, Chris-Johnston commented on docs/guides/commands/intro.md
> +> can cause gateway thread to be blocked; therefore, interrupting
```suggestion
> can cause the gateway thread to be blocked; therefore, interrupting
```

2020-01-16 09:28 UTC, Chris-Johnston commented on docs/guides/commands/namedarguments.md
> +The command can now be invoked as
```suggestion
The command can now be invoked with
```

2020-01-16 09:28 UTC, Chris-Johnston commented on docs/guides/commands/namedarguments.md
> +then the command can be invoked as
```suggestion
then the command can be invoked with
```

2020-01-16 09:28 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Messages/IMessage.cs
> +        ///         Do not fetch too many users at once! This may cause unwanted preemptive rate limit or even actual
```suggestion
        ///         Do not fetch too many users at once! This may cause an unwanted preemptive rate limit or even an actual
```

2020-01-16 09:28 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Messages/IMessage.cs
> +        ///     of flattening.
```suggestion
        ///     for flattening.
```

2020-01-27 05:13 UTC, Chris-Johnston approved these changes

2020-05-05 02:20 UTC, closed without merging