Feature: Include allowed mentions payload on message creation
RogueException/Discord.Net pull request #1455
Opened 2020-03-04 07:58 UTC by Chris-Johnston

This change implements the [allowed mentions object] for the payload of message creation, which allows for clients to specify which mentioned users and roles (including `@everyone`) will be notified when the message is sent.

The current version of this change is meant to be non-breaking to the SendMessageAsync interface, but it does not follow the pattern set by other methods where RequestOptions is the last optional parameter. Adding an overload didn't solve this issue as the interfaces became ambiguous.

[allowed mentions object]: https://discordapp.com/developers/docs/resources/channel#allowed-mentions-object

2020-05-05 02:20 UTC, Still34 requested changes

2020-05-05 02:20 UTC, Still34 commented on src/Discord.Net.Commands/ModuleBase.cs
> +        ///     Specifies if notifications are sent for mentioned users and roles in the message <paramref name="text"/>.
Incorrect paramref; should be `<paramref name="message"/>`.

2020-05-05 02:20 UTC, Still34 commented on src/Discord.Net.Core/Entities/Channels/IMessageChannel.cs
> +        ///     Specifies if notifications are sent for mentioned users and roles in the message <paramref name="text"/>. If <c>null</c>, all mentioned roles and users will be notified. If <c>null</c
Duplicated texts?

2020-05-05 02:20 UTC, Still34 commented on src/Discord.Net.Core/Entities/Messages/AllowedMentions.cs
> +        ///     The <see cref="AllowedMentionTypes.Users"/> flag is mutually exclusive with the <see cref="UserIds"/>
Might want to move specific details to `<remarks>`.

2020-05-05 02:20 UTC, Still34 commented on src/Discord.Net.Core/Entities/Messages/AllowedMentions.cs
> +        ///     Gets or sets the list of all role Ids that will be mentioned.
`ids` should be preferred as it is how we write it in the rest of the docs.

2020-05-06 04:02 UTC, Chris-Johnston commented
Thanks for the detailed review @Still34

2020-05-07 13:13 UTC, merged