Implemented include_roles for guilds/id/prune get&post
RogueException/Discord.Net pull request #1581
Opened 2020-06-26 17:43 UTC by RheaAyase

[docs](https://discord.com/developers/docs/resources/guild#get-guild-prune-count)
* Get Guild Prune Count
* Begin Guild Prune

Added missing `include_roles`.

Feedback welcome! (For instance I wasn't sure what would be preferred way of adding a list to the GET method.)

2020-07-07 22:00 UTC, SubZero0 requested changes

2020-07-07 22:00 UTC, SubZero0 commented on src/Discord.Net.Core/Entities/Guilds/IGuild.cs
> +        Task<int> PruneUsersAsync(int days = 30, bool simulate = false, ulong[] includeRoleIds = null, RequestOptions options = null);
Add it after `RequestOptions`, so it's accepted to be added without a major release and I would suggest changing it to `IEnumerable<ulong>`, so you could use Linq directly or arrays, would need to change some other places (and `.Any()` instead of Length).

2020-07-07 22:00 UTC, SubZero0 commented on src/Discord.Net.Rest/API/Rest/GuildPruneParams.cs
> +       [JsonProperty("include_roles")]
Missing one space.

2020-07-07 22:00 UTC, SubZero0 commented on src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs
> +        public Task<int> PruneUsersAsync(int days = 30, bool simulate = false, ulong[] includeRoleIds = null, RequestOptions options = null)
Same as `IGuild`.

2020-07-07 22:00 UTC, SubZero0 commented on src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs
> +        public Task<int> PruneUsersAsync(int days = 30, bool simulate = false, ulong[] includeRoleIds = null, RequestOptions options = null)
Same as `IGuild`.

2020-07-07 22:00 UTC, SubZero0 commented on src/Discord.Net.Core/Entities/Guilds/IGuild.cs
> +        /// <param name="includeRoleIds">An array of role IDs to include in the prune.</param>
I believe this could get a better description to what it does (from discord docs: "Any inactive user that has a subset of the provided role(s) will be counted in the prune and users with additional roles will not.").

Maybe "An array of role ids to be disconsidered and prune the users if they don't have additional roles.", @Still34 might have a better suggestion.

2020-07-11 14:21 UTC, RheaAyase commented on src/Discord.Net.Core/Entities/Guilds/IGuild.cs
> +        Task<int> PruneUsersAsync(int days = 30, bool simulate = false, ulong[] includeRoleIds = null, RequestOptions options = null);
I kept it as an array internal with the public methods ienumerable...

2020-11-07 18:55 UTC, merged