feature: Webhook message edit & delete functionality
RogueException/Discord.Net pull request #1753
Opened 2021-01-20 21:10 UTC by Desmont

In December Discord added the functionality for webhooks to edit and delete webhook messages ( https://discord.com/developers/docs/change-log#december-15-2020 ) - this PR adds this functionality.

2021-01-25 23:26 UTC, SubZero0 requested changes

2021-01-25 23:26 UTC, SubZero0 commented on src/Discord.Net.Rest/API/Rest/EditWebhookMessageParams.cs
> +    internal class EditWebhookMessageParams
Rename it to `ModifyWebhookMessageParams` and follow the same format as [ModifyMessageParams](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.Rest/API/Rest/ModifyMessageParams.cs) (optional content, missing `get; set;`, no constructor).

2021-01-25 23:26 UTC, SubZero0 commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +        public async Task EditWebhookMessageAsync(ulong webhookId, ulong messageId, EditWebhookMessageParams args, RequestOptions options = null)
`ModifyWebhookMessageAsync`.

2021-01-25 23:26 UTC, SubZero0 commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +            if (!args.Embeds.IsSpecified || args.Embeds.Value == null || args.Embeds.Value.Length == 0)
Remove this, you don't know how the current webhook message looks like (if it has content, embeds, a file...).

2021-01-25 23:26 UTC, SubZero0 commented on src/Discord.Net.Rest/API/Rest/EditWebhookMessageParams.cs
> +
Remove this empty line.

2021-01-25 23:26 UTC, SubZero0 commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +
Missing a precondition to limit the amount of embeds to a maximum of 10 if it's being specified.

2021-01-25 23:26 UTC, SubZero0 commented on src/Discord.Net.Webhook/DiscordWebhookClient.cs
> +        public Task EditMessageAsync(ulong messageId, string text = null, IEnumerable<Embed> embeds = null,
Rename it to `ModifyMessageAsync`.

2021-01-25 23:26 UTC, SubZero0 commented on src/Discord.Net.Webhook/WebhookClientHelper.cs
> +        public static async Task EditMessageAsync(DiscordWebhookClient client, ulong messageId, string text, IEnumerable<Embed> embeds,
Rename it to `ModifyMessageAsync`.

2021-01-25 23:32 UTC, SubZero0 requested changes
Forgot the xml docs.

2021-01-25 23:32 UTC, SubZero0 commented on src/Discord.Net.Webhook/DiscordWebhookClient.cs
> +        /// <summary> Edits a message posted using this webhook. </summary>
Missing parameter documentation, follow the same pattern as https://github.com/discord-net/Discord.Net/blob/e3850e1e8f0f24652f22cc6322329495707ff67f/src/Discord.Net.Core/Entities/Messages/IUserMessage.cs#L38-L49

2021-01-25 23:32 UTC, SubZero0 commented on src/Discord.Net.Webhook/DiscordWebhookClient.cs
> +        /// <summary> Deletes a message posted using this webhook. </summary>
Same as the other documentation.

2021-01-26 11:05 UTC, Desmont commented
Thanks for the feedback. I've made the changes that you requested.

2021-01-26 11:31 UTC, SubZero0 requested changes

2021-01-26 11:31 UTC, SubZero0 commented on src/Discord.Net.Rest/API/Rest/ModifyWebhookMessageParams.cs
> +        public string Content { get; set; }
It's `Optional<string>`.

2021-01-26 11:31 UTC, SubZero0 commented on src/Discord.Net.Webhook/DiscordWebhookClient.cs
> +        /// <summary> Modifies a message posted using this webhook. </summary>
Let the text be on its own line, like the remarks.

2021-01-26 11:31 UTC, SubZero0 commented on src/Discord.Net.Webhook/DiscordWebhookClient.cs
> +        /// <summary> Deletes a message posted using this webhook. </summary>
Let the text be on its own line, like the remarks.

2021-01-26 11:31 UTC, SubZero0 commented on src/Discord.Net.Webhook/DiscordWebhookClient.cs
> +        public Task ModifyMessageAsync(ulong messageId, string text = null, IEnumerable<Embed> embeds = null,
Actually, this needs to be changed, follow the same pattern as modifying user messages.
See the following: https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/Entities/Messages/SocketUserMessage.cs#L166-L167

They need to optionally change what they want, a simple "null" isn't able to tell if they want to clear it or not send at all.

2021-01-26 11:31 UTC, SubZero0 commented on src/Discord.Net.Webhook/WebhookClientHelper.cs
> +        public static async Task ModifyMessageAsync(DiscordWebhookClient client, ulong messageId, string text, IEnumerable<Embed> embeds,
Also needs to follow the same pattern as modifying user message like stated above.

2021-04-22 11:59 UTC, OFWModz commented
This does not solve the issue I created, please investigate before proposing a pull will solve an issue.

2021-04-28 13:15 UTC, SubZero0 approved these changes

2021-04-28 13:15 UTC, merged