Adding Entity guides, flowcharts, better sample system.
RogueException/Discord.Net pull request #2054
Opened 2022-01-21 15:32 UTC by Rozen4334

Adds a better approach to the glossary, including flowcharts & proper elaboration on unique entities. 
Adds a set of samples to the interaction framework, and renames the samples to make sense in respect of regular conventions.

Note: More samples will be introduced, the PR is not ready for merging.

2022-01-24 10:54 UTC, quinchs commented
![image](https://user-images.githubusercontent.com/49576606/150770150-8fdea256-c83e-4cfc-a22b-da3c7c3a715e.png)
Seems like IDN project is missing? Could you fix this please?

2022-01-24 10:57 UTC, Rozen4334 commented
Where is this missing? It appears to not be from my source. It builds on win but not on linux?

2022-01-24 10:58 UTC, quinchs commented
Take a look at the pipeline logs

2022-01-24 10:59 UTC, quinchs commented
![image](https://user-images.githubusercontent.com/49576606/150770813-f600c9bd-e2dd-4330-b599-bd250c5f84e8.png)
It also seems its removed from the SLN?

2022-01-24 13:40 UTC, Rozen4334 commented
Solved

2022-01-25 21:37 UTC, quinchs commented
going to wait for @lhjt's review

2022-01-26 16:30 UTC, lhjt requested changes
* With `docs/guides/entities/images/IUser.png`, there's an apostrophe missing for `doesnt` near the bottom right corner.

I'm being pretty pedantic with some minor things in this changeset, but it generally looks pretty good!

2022-01-26 16:30 UTC, lhjt commented on docs/guides/entities/casting.md
> +> Interfaces **can** be cast to other interfaces, as long as they inherit eachother.
```suggestion
> Interfaces **can** be cast to other interfaces, as long as they inherit each other.
```

2022-01-26 16:30 UTC, lhjt commented on docs/guides/entities/casting.md
> +> If the type you're casting to is null, a `NullReferenceException` will be thrown when its called.
```suggestion
> If the type you're casting to is null, a `NullReferenceException` will be thrown when it's called.
```

2022-01-26 16:30 UTC, lhjt commented on docs/guides/entities/glossary.md
> +* A **Rest Interaction Message** ([RestInteractionMessage]) is a message returned by the interactions' original response.
```suggestion
* A **Rest Interaction Message** ([RestInteractionMessage]) is a message returned by the interaction's original response.
```

2022-01-26 16:30 UTC, lhjt commented on docs/guides/entities/glossary.md
> +* A **Rest User Message** ([RestUserMessage]) is a message sent over rest, can be any of the above.
```suggestion
* A **Rest User Message** ([RestUserMessage]) is a message sent over rest; it can be any of the above.
```

2022-01-26 16:30 UTC, lhjt commented on docs/guides/entities/samples/casting.cs
> +// Say we have an entity, for the simplicity of this example, it will appear from thin air.
```suggestion
// Say we have an entity; for the simplicity of this example, it will appear from thin air.
```

2022-01-26 16:30 UTC, lhjt commented on docs/guides/entities/samples/restentities.cs
> +// RestUser entities expose the accentcolor and banner of a user.
```suggestion
// RestUser entities expose the accent color and banner of a user.
```

2022-01-26 16:30 UTC, lhjt commented on docs/guides/entities/samples/safety-cast-pass.cs
> +    // Because we do the above check inline (dont give the statement a body),
```suggestion
    // Because we do the above check inline (don't give the statement a body),
```

2022-01-26 16:30 UTC, lhjt commented on docs/guides/entities/samples/safety-cast-var.cs
> +// so we dont need to cast additionally inside of the statement.
```suggestion
// so we don't need to cast additionally inside of the statement.
```

2022-01-26 16:30 UTC, lhjt commented on samples/BasicBot/Program.cs
> +    // This is a minimal, bare-bones example of using Discord.Net
```suggestion
    // This is a minimal, bare-bones example of using Discord.Net.
```

2022-01-27 13:50 UTC, merged