Guides for Serilog and EFCore
RogueException/Discord.Net pull request #2134
Opened 2022-02-24 22:42 UTC by dukesteen

Hi everyone, this will be my first contribution to Discord.Net!

I have discussed with Rozen on discord about creating these two guides. Feel free to review and suggest changes.

2022-02-24 22:52 UTC, Rozen4334 requested changes

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/serilog.md
> +```cs
Sample into directory

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/serilog.md
> +```cs
Sample into directory

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/serilog.md
> +```cs
Sample into directory

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/serilog.md
> +    // var token = File.ReadAllText("token.txt")[0];
My own mistake on initial review. ReadAllText returns string, ReadAllLines returns array. [0] is not required.

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/serilog.md
> +  public static Task Main(string[] args) => new Program().MainAsync().GetAwaiter().GetResult();
May I suggest removing the `public` keyword, and making this `void`, so the entry point of this app is like any default console application format in standard2.1+?

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/efcore.md
> +```cs
Sample into directory

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/efcore.md
> +```cs
Sample into directory

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/efcore.md
> +```cs
Samples should go into /samples and referenced to as `[!code-csharp[title](samples/sample.cs)].`

2022-02-24 22:52 UTC, Rozen4334 commented on docs/guides/other_libs/serilog.md
> +For serilog to log discord events correctly, we have to map the discord `LogSeverity` to the serilog `LogEventLevel`. You can modify your log method to look like this.
Discord*, also suggest changing `we` for `you`

2022-02-24 23:09 UTC, dukesteen commented
Fixed all review points in [acd62f8](https://github.com/discord-net/Discord.Net/pull/2134/commits/acd62f84473ed93be931414b781f793b3f236628)

2022-02-24 23:15 UTC, Rozen4334 requested changes
Addressing the same grammatical issues as before, including another.

2022-02-24 23:15 UTC, Rozen4334 commented on docs/guides/other_libs/serilog.md
> +For serilog to log Discord events correctly, we have to map the discord `LogSeverity` to the serilog `LogEventLevel`. You can modify your log method to look like this.
Discord, Serilog*

2022-02-24 23:15 UTC, Rozen4334 commented on docs/guides/other_libs/samples/ConfiguringSerilog.cs
> +        // var token = File.ReadAllText("token.txt")[0];
Remove the `[0]`

2022-02-25 00:00 UTC, dukesteen commented
Fixed in [502eea8](https://github.com/discord-net/Discord.Net/pull/2134/commits/502eea898d8413deb6420800397de5c24c07198c)

2022-03-02 18:56 UTC, Rozen4334 commented
@quinchs this can be merged

2022-03-02 19:08 UTC, merged