InteractionService Feature: Passing CustomId matches into contexts
RogueException/Discord.Net pull request #2136
Opened 2022-02-25 19:38 UTC by Cenngo

This PR introduces a new interface called `IRouteMatchContainer`. This interface can be optionally implemented into Interaction Context types to allow the interaction service to inject the captured wild card values into an interaction context. Captured values are exposed to the user using a `IRouteSegmentMatch` collection and not as a `string[]` as a futureproofing measure. While this allows the users to access these values within preconditions, BeforeExecute, AfterExecute methods; ParameterPrecondition should be preferred to get and process individual parameter values.

2022-03-02 19:02 UTC, quinchs commented
@Cenngo Whats the status on this?

2022-03-02 19:09 UTC, Cenngo commented
> @Cenngo Whats the status on this?

To be honest i forgot about this after i started working on Discord-Net-Labs/Discord.Net-Labs#449 migration. Ill wrap this up and let you know.

2022-03-09 20:25 UTC, Cenngo commented
@quinchs This PR is in working state but i dont know if this change is necessary or if this is the best way to implement this. would like to hear your thoughts on this

2022-03-26 12:54 UTC, quinchs requested changes

2022-03-26 12:54 UTC, quinchs commented on src/Discord.Net.Core/Interactions/IRouteMatchContainer.cs
> +        public IEnumerable<IRouteSegmentMatch> SegmentMatches { get; }
```suggestion
        IEnumerable<IRouteSegmentMatch> SegmentMatches { get; }
```

2022-03-26 12:54 UTC, quinchs commented on src/Discord.Net.Core/Interactions/IRouteMatchContainer.cs
> +        public void SetSegmentMatches(IEnumerable<IRouteSegmentMatch> segmentMatches);
```suggestion
        void SetSegmentMatches(IEnumerable<IRouteSegmentMatch> segmentMatches);
```

2022-04-04 22:18 UTC, quinchs commented
cc @Rozen4334

2022-04-05 17:14 UTC, quinchs approved these changes

2022-04-05 17:26 UTC, Rozen4334 requested changes

2022-04-05 17:26 UTC, Rozen4334 commented on src/Discord.Net.Core/Interactions/IRouteMatchContainer.cs
> +    ///     Represents a container for temporarily storing CustomId wild card matches of a command name.
```suggestion
    ///     Represents a container for temporarily storing CustomId wild card matches of a component.
```

2022-04-05 17:26 UTC, Rozen4334 commented on src/Discord.Net.Core/Interactions/IRouteMatchContainer.cs
> +        ///     Sets the <see cref="SegmentMatches"/> propert
```suggestion
        ///     Sets the <see cref="SegmentMatches"/> property of this container.
```

2022-04-05 17:26 UTC, Rozen4334 commented on src/Discord.Net.Core/Interactions/IRouteSegmentMatch.cs
> +    ///     Represents an object for storing CustomId a wild card match.
```suggestion
    ///     Represents an object for storing a CustomId wild card match.
```

2022-04-05 17:26 UTC, Rozen4334 commented on src/Discord.Net.Core/Interactions/IRouteSegmentMatch.cs
> +        /// </summary>
```suggestion
        /// </summary>
        /// <returns>
        ///    The value of this wild card.
        /// </returns>
```

2022-04-05 17:26 UTC, Rozen4334 commented on src/Discord.Net.Core/Interactions/IRouteMatchContainer.cs
> +        /// </summary>
```suggestion
        /// </summary>
        /// <returns>
        ///    A collection of captured route segments.
        ///</returns>
```

2022-04-05 17:26 UTC, Rozen4334 commented on src/Discord.Net.Core/Interactions/IRouteMatchContainer.cs
> +        ///     Gets the collection of the captured route segments.
```suggestion
        ///     Gets the collection of captured route segments in this container.
```

2022-04-05 17:26 UTC, Rozen4334 commented on src/Discord.Net.Core/Interactions/IRouteSegmentMatch.cs
> +        ///     Gets the captured value.
```suggestion
        ///     Gets the captured value of this wild card match.
```

2022-04-05 17:26 UTC, Rozen4334 commented on src/Discord.Net.Core/Interactions/RouteSegmentMatch.cs
> +    ///     Represents an object for storing CustomId wild card matches.
```suggestion
    ///     Represents an object for storing a CustomId wild card match.
```

2022-04-18 09:45 UTC, Rozen4334 approved these changes
lgtm

2022-04-27 14:09 UTC, merged