MediatR Guide + sample
RogueException/Discord.Net pull request #2218
Opened 2022-03-31 15:04 UTC by dukesteen

This PR introduces a guide to adding MediatR to your Discord.Net bot. it goes over adding MediatR to your DI container, creating an event listener, registering said event listener inside your DI container, notifications, and notification handlers.

2022-03-31 15:43 UTC, csmir requested changes

2022-03-31 15:43 UTC, Rozen4334 commented on docs/guides/other_libs/samples/MediatrCreatingMessageNotification.cs
> +namespace Viscoin.Bot.Infrastructure.Messages;
`namespace MediatRSample.Notifications;`

2022-03-31 15:43 UTC, csmir commented on docs/guides/other_libs/mediatr.md
> +To add more event types you can follow these steps
'steps:'

2022-03-31 15:43 UTC, csmir commented on docs/guides/other_libs/mediatr.md
> +2. Register the event in your `DiscordEventListener` class
'class.'

2022-03-31 15:43 UTC, csmir commented on docs/guides/other_libs/samples/MediatrDiscordEventListener.cs
> +    public Task StartAsync()
`public async Task StartAsync()` considering this call is awaited in `Program.cs`

2022-03-31 15:43 UTC, csmir commented on docs/guides/other_libs/samples/MediatrDiscordEventListener.cs
> +        return Task.CompletedTask;
`await Task.CompletedTask;`

2022-03-31 15:43 UTC, csmir commented on docs/guides/other_libs/samples/MediatrMessageReceivedHandler.cs
> +
`using System;`

2022-03-31 15:43 UTC, csmir commented on docs/guides/other_libs/samples/MediatrDiscordEventListener.cs
> +    private Task OnMessageReceivedAsync(SocketMessage arg)
if `Mediator.Publish` is a `Task`, we should not block the gateway task here, I do not know if disposal is already done within the publishment?

2022-03-31 15:43 UTC, csmir commented on docs/guides/other_libs/samples/MediatrDiscordEventListener.cs
> +
`using System.Threading;`
`using System.Threading.Tasks;`

2022-03-31 15:43 UTC, Rozen4334 commented on docs/guides/other_libs/mediatr.md
> +MediatR publishes notifications to all of your notification handlers that are listening for a specific notification. We will create a handler for our newly created `MessageReceivedNotification` like
'this:'

2022-03-31 15:43 UTC, Rozen4334 commented on docs/guides/other_libs/mediatr.md
> +For MediatR to actually publish the events we need a way to listen for them. We will create a class to listen for discord events like so.
'so:'

2022-03-31 15:43 UTC, Rozen4334 commented on docs/guides/other_libs/mediatr.md
> +You can install the following packages through your IDE or go to the nuget link to grab the dotnet cli command.
'NuGet'

2022-03-31 15:57 UTC, dukesteen commented
Fixed in [b586319](https://github.com/discord-net/Discord.Net/pull/2218/commits/b58631905c1f03f99c55edccaae4770cf3ccead8)

2022-04-05 17:16 UTC, Rozen4334 approved these changes
lgtm

2022-04-05 17:18 UTC, quinchs approved these changes

2022-04-05 17:18 UTC, merged