Add Parse & TryParse to EmbedBuilder.
RogueException/Discord.Net pull request #2284
Opened 2022-05-03 11:05 UTC by Rozen4334

Introduces a method that allows users to parse embedbuilders directly from text. (json)

2022-05-04 17:48 UTC, kamilosxp approved these changes

2022-05-10 01:54 UTC, quinchs requested changes

2022-05-10 01:54 UTC, quinchs commented on src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
> +            var model = JsonConvert.DeserializeObject<Embed>(json);
should this be try-catched and return false on exception?

2022-05-10 01:54 UTC, quinchs commented on src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
> +        /// <returns>An <see cref="EmbedBuilder"/> with populated values from the passed <paramref name="json"/></returns>
```suggestion
        /// <returns>An <see cref="EmbedBuilder"/> with populated values from the passed <paramref name="json"/>.</returns>
```

2022-05-10 01:54 UTC, quinchs commented on src/Discord.Net.Rest/Extensions/StringExtensions.cs
> +            => JsonConvert.SerializeObject(embed.ToModel(), formatting, new EmbedTypeConverter());
The custom contract resolver should be used here

2022-05-18 07:54 UTC, quinchs approved these changes

2022-05-18 07:54 UTC, quinchs commented on src/Discord.Net.Rest/Extensions/StringExtensions.cs
> +        /// <returns>A Json <see langword="string"/> containing the data from the <paramref name="builder"/>.</returns>
```suggestion
        /// <returns>A Json <see langword="string"/> containing the data from the <paramref name="embed"/>.</returns>
```

2022-05-18 07:57 UTC, merged