Update EmbedBuilder.cs
RogueException/Discord.Net pull request #2345
Opened 2022-06-03 00:47 UTC by Hampo

Fixes a bug where 'EmbedBuilder.Length' will throw an exception of type 'System.NullReferenceException' when a field doesn't have a value.

2022-08-01 15:44 UTC, Rozen4334 approved these changes

2022-08-01 17:34 UTC, Cenngo requested changes

2022-08-01 17:34 UTC, Cenngo commented on src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
> +                int fieldSum = Fields.Sum(f => f.Name.Length + (f.Value == null ? 0 : f.Value.ToString()?.Length ?? 0));
the initial null check seems redundant. `f.Value?.ToString().Length ?? 0` should be enough. Can you please verify whether that works or not and update your code if so.

2022-08-21 12:01 UTC, Rozen4334 commented
Could you please continue this PR and take up @Cenngo 's review?

2022-08-21 16:29 UTC, Cenngo approved these changes

2022-09-02 21:28 UTC, quinchs approved these changes

2022-09-04 06:46 UTC, merged