Support the WEBHOOKS_UPDATED event
RogueException/Discord.Net pull request #2384
Opened 2022-07-11 04:40 UTC by CottageDwellingCat

The `WEBHOOKS_UPDATE` event is ignored by socket clients, and a comment claims it is user only, however it is [documented](https://discord.com/developers/docs/topics/gateway#webhooks-update) and other libraries appear to [support it](https://github.com/discordjs/discord.js/blob/e78c9c9ee9626b5aad7cbbd551bcdef666c11828/packages/discord.js/src/client/actions/WebhooksUpdate.js#L6). The event is useful in webhook caching solutions that need to know if a webhook was moved.
The ignored event is found at: https://github.com/discord-net/Discord.Net/blob/a890de93044cb5db12e64fce203e718286d8dd83/src/Discord.Net.WebSocket/DiscordSocketClient.cs#L2861-L2864

Example using the event:
```cs
client.WebhooksUpdated += async (guild, channel) =>
{
    Console.ForegroundColor = ConsoleColor.Magenta;
    Console.WriteLine($"A webhook was updated in or moved to {guild}#{channel}");
    Console.ResetColor();
    await Task.CompletedTask;
};
```

2022-07-18 17:38 UTC, MrCakeSlayer approved these changes

2022-08-01 15:33 UTC, Rozen4334 approved these changes

2022-08-01 15:37 UTC, Rozen4334 requested changes

2022-08-01 15:37 UTC, Rozen4334 commented on src/Discord.Net.WebSocket/API/Gateway/WebhooksUpdatedEvent.cs
> +        public ulong ChanelId { get; set; }
```suggestion
        public ulong ChannelId { get; set; }
```

2022-08-01 15:38 UTC, merged