Interactions Command Localization
RogueException/Discord.Net pull request #2395
Opened 2022-07-21 14:56 UTC by Cenngo

This PR adds Application Command localization to Core, Rest and WebSocket projects. Introduces a `ILocalizationManger` interface and default Localization Managers for Json and ResX in preperation for the Slash Commands localization feature release.

Two LocalizationManagers ship with this update, JsonLocalizationManager and ResxLocalizationManager.

JsonLocaliationManager uses a nested data structure similar to Discord's Application Commands schema. You can get the Json schema [here](https://gist.github.com/Cenngo/d46a881de24823302f66c3c7e2f7b254). LocalizationManager accepts a base path and a base file name and automatically discovers every resource file ( `\basePath\fileName.locale.json`  ). 

```json
{
    "command_1":{
        "name": "localized_name",
        "description": "localized_description",
        "parameter_1":{
            "name": "localized_name",
            "description": "localized_description"
        }
    },
    "group_1":{
        "name": "localized_name",
        "description": "localized_description",
        "command_1":{
            "name": "localized_name",
             "description": "localized_description",
             "parameter_1":{
                 "name": "localized_name",
                  "description": "localized_description"
            },
            "parameter_2":{
                 "name": "localized_name",
                  "description": "localized_description"
            }
        }
    }
}
```

ResxLocalizationManager uses the [naming scheme](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-6.0#resource-file-naming) used by ASP.NET ( `group1\command1\parameter2.fr-FR.resx` or  `group1.command1.parameter2.fr-FR.resx` ). Every resx file must have two fields: name and description. Individual .resx files can be defined for every group/command/parameter. Space characters within Context command names are tokenized with tilde character.

Interaction Service can be easily configured to use any `ILocalizationManager` implementation by setting the LocalizationManager field of InteractionServiceConfig.

## TODO
- [x] Add per-request header support to rest client(#2261)
- [x] Add localization support to parameter choices
- [ ] Add locale parameter to Get*ApplicationCommandsAsync methods for fetching localized name and description strings

## Breaking Changes
```diff
- A new requestHeaders parameter is added to every Send* method of IRestClient.
```

2022-08-01 16:02 UTC, Rozen4334 requested changes

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Guilds/IGuild.cs
> +        /// <param name="locale">The target locale of the localized name and description fields. Sets <c>X-Discord-Locale</c> header, which takes precedence over <c>Accept-Language</c>.</param>
```suggestion
        /// <param name="locale">The target locale of the localized name and description fields. Sets the <c>X-Discord-Locale</c> header, which takes precedence over <c>Accept-Language</c>.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/ContextMenus/MessageCommandBuilder.cs
> +        /// <param name="nameLocalizations">Localization dictionary for the name field of this command.</param>
```suggestion
        /// <param name="nameLocalizations">The localization dictionary to use for the name field of this command.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/ContextMenus/UserCommandBuilder.cs
> +        /// <param name="nameLocalizations">Localization dictionary for the name field of this command.</param>
```suggestion
        /// <param name="nameLocalizations">The localization dictionary to use for the name field of this command.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOption.cs
> +        ///     Gets the localization dictionary for the name field of this command.
```suggestion
        ///     Gets the localization dictionary for the name field of this command option.
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOption.cs
> +        ///     Gets the localization dictionary for the description field of this command.
```suggestion
        ///     Gets the localization dictionary for the description field of this command option.
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOption.cs
> +        ///     Gets the localized name of this command.
```suggestion
        ///     Gets the localized name of this command option.
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOption.cs
> +        ///     Gets the localized description of this command.
```suggestion
        ///     Gets the localized description of this command option.
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOptionChoice.cs
> +        ///     Gets the localization dictionary for the name field of this command.
```suggestion
        ///     Gets the localization dictionary for the name field of this command option.
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/IApplicationCommandOptionChoice.cs
> +        ///     Gets the localized name of this command.
```suggestion
        ///     Gets the localized name of this command option.
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
> +        /// <param name="nameLocalizations">Localization dictionary for the name field of this command.</param>
```suggestion
        /// <param name="nameLocalizations">The localization dictionary to use for the name field of this command.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
> +        /// <param name="descriptionLocalizations">Localization dictionary for the name field of this command.</param>
```suggestion
        /// <param name="descriptionLocalizations">The localization dictionary to use for the description field of this command.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
> +        /// <param name="nameLocalizations">Localization dictionary for the description field of this command.</param>
```suggestion
        /// <param name="nameLocalizations">The localization dictionary to use for the name field of this command option choice.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
> +        /// <param name="nameLocalizations">Localization dictionary for the description field of this command.</param>
```suggestion
        /// <param name="nameLocalizations">The localization dictionary to use for the name field of this command option choice.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
> +        /// <param name="nameLocalizations">Localization dictionary for the name field of this command.</param>
```suggestion
        /// <param name="nameLocalizations">The localization dictionary to use for the name field of this command option.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
> +        /// <param name="descriptionLocalizations">Localization dictionary for the description field of this command.</param>
```suggestion
        /// <param name="descriptionLocalizations">The localization dictionary to use for the description field of this command option.</param>
```

2022-08-01 16:02 UTC, csmir commented on src/Discord.Net.Interactions/LocalizationManagers/ILocalizationManager.cs
> +    ///     Respresents localization provider for Discord Application Commands.
```suggestion
    ///     Respresents a localization provider for Discord Application Commands.
```

2022-08-01 16:02 UTC, Rozen4334 commented on src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
> +        /// <param name="nameLocalizations">Localization dictionary for the description field of this command.</param>
```suggestion
        /// <param name="nameLocalizations">The localization dictionary for to use the name field of this command option choice.</param>
```

2022-08-01 16:02 UTC, Rozen4334 commented on src/Discord.Net.Core/Entities/Interactions/SlashCommands/SlashCommandBuilder.cs
> +        /// <param name="nameLocalizations">Localization dictionary for the description field of this command.</param>
```suggestion
        /// <param name="nameLocalizations">The localization dictionary for to use the name field of this command option choice.</param>
```

2022-08-01 20:44 UTC, MrCakeSlayer commented
@Cenngo perhaps include some docs/guide for this update as well?

2022-08-01 20:52 UTC, Rozen4334 reviewed
XML lgtm, but awaiting to approve until I've verified functionality. Going try to build an app on localization for testing

2022-08-01 21:14 UTC, Cenngo commented
> XML lgtm, but awaiting to approve until I've verified functionality. Going try to build an app on localization for testing

i also need to do that myself. its been a while since i lasted tested this PR and im sure discord broke a thing or two since then

2022-08-23 08:40 UTC, Rozen4334 approved these changes

2022-08-26 15:45 UTC, merged