[Feature] Refactor `SendMessageAsync` & `SendFile(s)Async` methods & modify webhook message attachments
RogueException/Discord.Net pull request #2609
Opened 2023-02-21 14:51 UTC by Misha-133

This PR brings numerous changes to D.Net internals to improve consistency across the API and as well adds support for modifying attachments of a webhook message.

### Changes
- update send message requirements to have at least one of `Content`, `Embeds`, `Stickers`, `Attachments` or `Components`
- unify `SendMessageAsync` & `SendFile(s)Async` methods' validations to have same requirements & error messages
- update all `SendFile(s)Async` methods' `text` parameter to have default `null` value & properly handle it.  **existing code will need to be recompiled**
- update XmlDocs to include `MessageFlags.SuppressNotification` option for `flags`
- update `DiscordWebhookClient.ModifyMessageAsync` to allow modifying webhook message attachments
- (internal) refactor `DiscordWebhookClient` xmldocs to make them readable

2023-02-27 13:13 UTC, csmir requested changes

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +            if ((!args.Embeds.IsSpecified || args.Embeds.Value == null || args.Embeds.Value.Length == 0)
Add a new Precondition for these checks. AtLeastAny for example, which does this check rather than throwing exceptions in the api methods.

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +            if ((!args.Embeds.IsSpecified || args.Embeds.Value == null || args.Embeds.Value.Length == 0)
Same argument

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +            if ((!args.Embeds.IsSpecified || args.Embeds.Value == null || args.Embeds.Value.Length == 0)
Same argument

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +                throw new ArgumentException(message: $"Message content is too long, length must be less or equal to {DiscordConfig.MaxMessageSize}.", paramName: nameof(args.Content));
Same argument

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +                throw new ArgumentException(message: $"Message content is too long, length must be less or equal to {DiscordConfig.MaxMessageSize}.", paramName: nameof(args.Content));
Same argument

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +            if ((!args.Embeds.IsSpecified || args.Embeds.Value == null || args.Embeds.Value.Length == 0)
Same argument

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +                throw new ArgumentException(message: $"Message content is too long, length must be less or equal to {DiscordConfig.MaxMessageSize}.", paramName: nameof(args.Content));
This should also be a precondition, AtMost in this case. Might as well settle this now for all occurences.

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
>                  throw new ArgumentException(message: $"Message content is too long, length must be less or equal to {DiscordConfig.MaxMessageSize}.", paramName: nameof(args.Content));
Same argument

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +            if (args.Content.IsSpecified && args.Content.Value is not null && args.Content.Value.Length > DiscordConfig.MaxMessageSize)
Same argument

2023-02-27 13:13 UTC, csmir commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
>                  throw new ArgumentException(message: $"Message content is too long, length must be less or equal to {DiscordConfig.MaxMessageSize}.", paramName: nameof(args.Content));
Same argument

2023-02-27 17:59 UTC, Misha-133 commented on src/Discord.Net.Rest/DiscordRestApiClient.cs
> +            if ((!args.Embeds.IsSpecified || args.Embeds.Value == null || args.Embeds.Value.Length == 0)
Should be resolved now

2023-03-31 11:25 UTC, csmir approved these changes

2023-03-31 11:26 UTC, merged