[Fix] some `ReplyAsync` methods missing `MessageFlags` parameter
RogueException/Discord.Net pull request #2713
Opened 2023-06-29 18:01 UTC by Misha-133

This PR adds missing `MessageFlags` parameter to `ReplyAsync` methods

2023-07-28 18:22 UTC, rarDevelopment approved these changes

2023-07-29 00:40 UTC, rarDevelopment commented
Any chance this could get looked at sooner than later? Holding up a feature update for this change 😄

2023-08-10 12:32 UTC, quinchs requested changes

2023-08-10 12:32 UTC, quinchs commented on src/Discord.Net.Core/Extensions/MessageExtensions.cs
> +        public static async Task<IUserMessage> ReplyAsync(this IUserMessage msg, string text = null, bool isTTS = false, Embed embed = null, AllowedMentions allowedMentions = null, RequestOptions opt
Missing doc

2023-08-10 12:52 UTC, quinchs approved these changes

2023-08-10 12:54 UTC, merged