[Feature] New `ModifyCurrentApplication` features
RogueException/Discord.Net pull request #2730
Opened 2023-07-14 11:26 UTC by Misha-133

[Docs PR](https://github.com/discord/discord-api-docs/pull/6297)

This PR adds some newly documented features for `Edit Current Application` endpoint.

### Changes
- Add new editable properties
- Add some missing xmldocs
- Make the constructor of `ApplicationInstallParams` public, so it can be used to modify the app
- `ApplicationInstallParams.Permission` is not nullable

2023-07-14 19:10 UTC, Panthr75 requested changes

2023-07-14 19:10 UTC, Panthr75 commented on src/Discord.Net.Core/Entities/Applications/ApplicationInstallParams.cs
> +    public ApplicationInstallParams(string[] scopes, GuildPermission permission)
Might want to add a null check to `scopes`, each item in `scopes`, and maybe even validation of scopes (e.g `application.blow_up` isn't a valid scope)

2023-07-14 19:10 UTC, Panthr75 commented on src/Discord.Net.Rest/ClientHelper.cs
>              if(args.Description.IsSpecified)
Add space between `if` and `(` like you did on line 32

2023-07-15 00:40 UTC, Panthr75 requested changes
What about adding a builder type for building the scopes that you can pass into `ApplicationInstallParams` so that you can get the benefit of knowing the scopes you can use and the option of specifying new scopes that they release indirectly?

Example mock class:
```cs
class ApplicationScopesBuilder
{
    private readonly List<string> _scopes = new();
    
    public bool ReadActivities
    {
        get => HasScope("activities.read");
        set => SetScope("activities.read", value);
    }

    public bool WriteActivities
    {
        get => HasScope("activities.write");
        set => SetScope("activities.write", value);
    }

    public bool ReadBuildsApplications
    {
        get => HasScope("applications.builds.read");
        set => SetScope("applications.builds.read", value);
    }

    public bool UploadBuildsApplications
    {
        get => HasScope("applications.builds.upload");
        set => SetScope("applications.builds.upload", value);
    }

    public bool CommandsApplications
    {
        get => HasScope("applications.commands");
        set => SetScope("applications.commands", value);
    }

    public bool UpdateCommandsApplications
    {
        get => HasScope("applications.commands.update");
        set => SetScope("applications.commands.update", value);
    }

    public bool UpdatePermissionsCommandsApplications
    {
        get => HasScope("applications.commands.permissions.update");
        set => SetScope("applications.commands.permissions.update", value);
    }

    public bool EntitlementsApplications
    {
        get => HasScope("applications.entitlements");
        set => SetScope("applications.entitlements", value);
    }

    public bool UpdateStoreApplications
    {
        get => HasScope("applications.store.update");
        set => SetScope("applications.store.update", value);
    }

    public bool Bot
    {
        get => HasScope("bot");
        set => SetScope("bot", value);
    }

    public bool Connections
    {
        get => HasScope("connections");
        set => SetScope("connections", value);
    }

    public bool ReadDm_channels
    {
        get => HasScope("dm_channels.read");
        set => SetScope("dm_channels.read", value);
    }

    public bool Email
    {
        get => HasScope("email");
        set => SetScope("email", value);
    }

    public bool JoinGdm
    {
        get => HasScope("gdm.join");
        set => SetScope("gdm.join", value);
    }

    public bool Guilds
    {
        get => HasScope("guilds");
        set => SetScope("guilds", value);
    }

    public bool JoinGuilds
    {
        get => HasScope("guilds.join");
        set => SetScope("guilds.join", value);
    }

    public bool ReadMembersGuilds
    {
        get => HasScope("guilds.members.read");
        set => SetScope("guilds.members.read", value);
    }

    public bool Identify
    {
        get => HasScope("identify");
        set => SetScope("identify", value);
    }

    public bool ReadMessages
    {
        get => HasScope("messages.read");
        set => SetScope("messages.read", value);
    }

    public bool ReadRelationships
    {
        get => HasScope("relationships.read");
        set => SetScope("relationships.read", value);
    }

    public bool WriteRole_connections
    {
        get => HasScope("role_connections.write");
        set => SetScope("role_connections.write", value);
    }

    public bool Rpc
    {
        get => HasScope("rpc");
        set => SetScope("rpc", value);
    }

    public bool WriteActivitiesRpc
    {
        get => HasScope("rpc.activities.write");
        set => SetScope("rpc.activities.write", value);
    }

    public bool ReadNotificationsRpc
    {
        get => HasScope("rpc.notifications.read");
        set => SetScope("rpc.notifications.read", value);
    }

    public bool ReadVoiceRpc
    {
        get => HasScope("rpc.voice.read");
        set => SetScope("rpc.voice.read", value);
    }

    public bool WriteVoiceRpc
    {
        get => HasScope("rpc.voice.write");
        set => SetScope("rpc.voice.write", value);
    }

    public bool Voice
    {
        get => HasScope("voice");
        set => SetScope("voice", value);
    }

    public bool IncomingWebhook
    {
        get => HasScope("webhook.incoming");
        set => SetScope("webhook.incoming", value);
    }
    
    public void SetScope(string scopeName, bool value)
    {
        if (value) AddScope(scopeName);
        else RemoveScope(scopeName);
    }

    public void RemoveScope(string scopeName)
    {
        if (scopeName is null) return;
        _scopes.Remove(scopeName.ToLower());
    }
    
    public void AddScope(string scopeName)
    {
        if (scopeName is null) return;
        scopeName = scopeName.ToLower();
        
        if (!_scopes.Contains(scopeName)) _scopes.Add(scopeName);
    }
    
    public bool HasScope(string scopeName)
    {
        return scopeName is null ? false : _scopes.Contains(scopeName);
    }
}
```

2023-07-15 00:40 UTC, Panthr75 commented on src/Discord.Net.Core/Entities/Applications/ApplicationInstallParams.cs
> +        Preconditions.NotNull(scopes, nameof(scopes));
But what about the values inside the array?

2023-08-10 13:00 UTC, quinchs approved these changes

2023-08-10 13:00 UTC, quinchs commented on src/Discord.Net.Core/Entities/Applications/IApplication.cs
> +        ///     Gets a collection of install parameters for this application. <see langword="null"/> if disabled.
```suggestion
        ///     Gets a collection of install parameters for this application; <see langword="null"/> if disabled.
```

2023-08-10 13:18 UTC, merged