[Feature] Voice reconnection and resuming
RogueException/Discord.Net pull request #2873
Opened 2024-03-08 18:02 UTC by Lepterion

### Description
This PR adds missing reconnection and resume features to the AudioClient.
1. Now the client reconnects when it's moved between channels (when a `VOICE_STATE_UPDATE` message saying the bot changed it's channel, following by `VOICE_SERVER_UPDATE` messages are received)
2. When a connection was terminated and close code != `4001`, `4002`, `4003`, `4004`, `4005`, `4006`, `4009`, `4012`, `4016`, the client'll try to resume lost connection. If it can't, the connection's stopped and the consumer needs to reconnect the client manually.
3. `Disconnected` event will now be invoked only in this cases:
    a. Client was disconnected by the consumer.
    b. Bot user was disconnected from the voice channel.
    c. Resuming failed.

### Changes

**AudioClient**:
- added constant `BlacklistedResumeCodes`
- added enum `StopReason`
- added state fields: `_stopReason` and `_resuming` for disconnection control
- don't forward `ConnectionManager.Disconnected` to `AudioClient.Disconnected`. This is done manually
- method `StopAsync()` now calls internal overload `StopAsync(StopReason)` with `StopReason.Normal`
- in `OnConnectingAsync()` depending on the `_resuming` value send either Identity or Resume message
- added stop reason handling in the `OnDisconnectingAsync(Exception)` method
- added methods `FinishDisconnect` and `ClearHeartBeaters` in order to make disconnect handling look better
- cleaning up `_keepaliveTimes`
- added method `WaitForDisconnectAsync(TimeSpan)`
- handling `OpCode 9 Resumed` websocket message

**ConnectionManager**
- swapped lines `175` and `176`. This _shouldn't_ affect anything but makes handling disconnection easier.

**DiscordVoiceApiClient**
- added method `SendResume`

**SocketGuild**
- in `AddOrUpdateVoiceStateAsync` stop the audio connection if moved or disconnected
- in `FinishConnectAudio` if the connection is still active, wait until it closes (Doesn't block the gateway unless something's wrong)

**Other**
- added class Discord.API.Voice.ResumeParams

### Related Issues

idk, this might be mentioned somewhere, but I couldn't find any related issues on GitHub.

2024-03-08 18:07 UTC, Lepterion commented
Why builds failed 💀

2024-03-08 18:09 UTC, Misha-133 commented
> builds failed 💀 ??????

The old pipeline runs on .NET 6 and thus doesn't support .net7+ features
One of those being collection expressions

2024-03-08 18:12 UTC, Lepterion commented
> > builds failed 💀 ??????
> 
> The old pipeline runs on .NET 6 and thus doesn't support .net7+ features One of those being collection expressions

How can I find out where is the problem?

2024-03-08 18:13 UTC, Misha-133 commented
> > > builds failed 💀 ??????
> > 
> > 
> > The old pipeline runs on .NET 6 and thus doesn't support .net7+ features One of those being collection expressions
> 
> How can I find out where is the problem?

![image](https://github.com/discord-net/Discord.Net/assets/61027276/93d6d662-dbc6-4876-a530-7f600b2b67ac)
![image](https://github.com/discord-net/Discord.Net/assets/61027276/d3f7cc76-7da4-4d56-870c-b11fab75d5d0)
![image](https://github.com/discord-net/Discord.Net/assets/61027276/2623504c-3a0d-471b-a7e6-a6321e75d4b1)
![image](https://github.com/discord-net/Discord.Net/assets/61027276/7a30d73b-4fc9-4ba0-91c8-c30485e877b0)

2024-03-08 18:22 UTC, Lepterion commented
@Misha-133 resolved

2024-03-11 15:45 UTC, Misha-133 commented
@Lepterion 
Thanks for updating this ancient part of DNet

I have a couple of questions tho.
1. Could it be possible to keep the input stream in case of reconnects/channel switches? 
2. While testing this I got a 
```cs
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext() in H:\github\Discord.Net\src\Discord.Net.WebSocket\ConnectionManager.cs:line 79
```
and 
```cs
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external, Boolean disconnect) in H:\github\Discord.Net\src\Discord.Net.WebSocket\Entities\Guilds\SocketGuild.cs:line 1802
   at Discord.WebSocket.SocketGuild.ConnectAudioAsync(UInt64 channelId, Boolean selfDeaf, Boolean selfMute, Boolean external, Boolean disconnect) in H:\github\Discord.Net\src\Discord.Net.WebSocket\Entities\Guilds\SocketGuild.cs:line 1807
```
repro steps:
- connect the bot to a voice channel
- move the bot to another channel through the UI
- call `ConnectAsync` on the channel the bot was moved to

2024-03-11 17:02 UTC, Lepterion commented
@Misha-133
1. I think no, because of session changes which cause change of sodium secrets.
2. If it's a log message, probably, connection manager raises critical error in the task completion source. Technically, this can be resolved but idk if some of dnet's gateway features use this, so I'm afraid of modifying the connection manager.

2024-03-11 17:09 UTC, Lepterion commented
@Misha-133 task csncelled exception can be neverminded

2024-03-11 17:09 UTC, Misha-133 commented
> I think no, because of session changes which cause change of sodium secrets.

Yeah, but we could keep the stream alive on out end
So the playback can continue after resuming
Otherwise
> don't forward `ConnectionManager.Disconnected` to `AudioClient.Disconnected`. This is done manually

would be a breaking change.

2024-03-11 17:11 UTC, Lepterion commented
> would be a breaking change.

Is this very bad?

2024-03-11 17:13 UTC, Misha-133 commented
We can't make breaking changes on non-major version bumps

2024-03-11 17:14 UTC, Lepterion commented
@Misha-133 I can create `Finished` event which will be invoked only when needed. `Disconnected` will be invoked on every connection termination.

2024-03-11 17:16 UTC, Misha-133 commented
> @Misha-133 I can create `Finished` event which will be invoked only when needed. `Disconnected` will be invoked on every connection termination.

That would still be a breaking change

2024-03-11 17:24 UTC, Lepterion commented
> That would still be a breaking change

The reason for changing event's behaviour is that every time `Disconnected` is invoked, the client gets disposed. I can use audio client's internal state to resolve this issue instead of changing events.

2024-03-11 17:47 UTC, Lepterion commented
> I can use audio client's internal state to resolve this issue instead of changing events.

@Misha-133 commited with this thing implemented

2024-03-12 19:28 UTC, Lepterion commented
@Misha-133 so what do you think?

2024-03-12 19:29 UTC, Misha-133 commented
Yeah sorry for the delay, I'll take a look at it *later*

2024-03-14 08:42 UTC, Misha-133 requested changes

2024-03-14 08:42 UTC, Misha-133 commented on src/Discord.Net.WebSocket/Audio/AudioClient.cs
> +        /// Waits until all post-disconnect actions are done.
```suggestion
        ///     Waits until all post-disconnect actions are done.
```

2024-03-14 08:42 UTC, Misha-133 commented on src/Discord.Net.WebSocket/Audio/AudioClient.cs
> +        /// <returns>A <see cref="Task"/> that represents an asynchronous process of waiting.</returns>
```suggestion
        /// <returns>
        ///     A <see cref="Task"/> that represents an asynchronous process of waiting.
        /// </returns>
```

2024-03-14 08:44 UTC, Misha-133 commented
Could you merge `dev` into this branch? so the workflow get's triggered

2024-03-14 09:22 UTC, Lepterion commented
> Could you merge `dev` into this branch? so the workflow get's triggered

Dnet's dev into this?

2024-03-14 09:26 UTC, Lepterion commented
@Misha-133 done

2024-03-14 09:33 UTC, Misha-133 approved these changes

2024-03-14 09:33 UTC, merged