Parameter preconditions and typereader overriding
RogueException/Discord.Net pull request #364
Opened 2016-11-19 15:49 UTC by FiniteReality

Using the new command builder system, since I'm not sure whether Joe4evr is going to update his system.

Parameter preconditions had to be done as part of the execute phase as they require the value passed to the command after parsing - I wasn't sure about the best way to include it as a separate phase as it would have meant changing how the parameter list was built and passed around heavily.

2016-11-21 18:52 UTC, FiniteReality commented
So, I'm a derp and didn't test properly; the latest commit fixes the mistakes I made.

2016-11-25 18:07 UTC, Auralytical requested changes

2016-11-25 18:07 UTC, RogueException commented on src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs
> +                var reader = readers?.FirstOrDefault();
Is it safe to always assume the first reader is the default? Maybe we should have a separate field for the default/global reader?

2016-11-25 18:07 UTC, RogueException commented on src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs
> +                var reader = readers?.FirstOrDefault();
It seems you're using ConcurrentBags which, by definition, do not guarantee any ordering.

2016-11-25 18:07 UTC, RogueException commented on src/Discord.Net.Commands/Info/CommandInfo.cs
> +            try
It's safe to leave this try-catch around the whole op, instead of splitting it into two sections.

2016-11-27 04:14 UTC, Auralytical approved these changes

2016-11-27 04:14 UTC, RogueException commented
If this has been retested, PR is approved once conflicts are resolved.

2016-12-07 19:17 UTC, FiniteReality commented
@RogueException Any news on merging this? As far as I'm aware this is ready

2016-12-08 01:39 UTC, merged