Fix a bunch of command/alias issues
RogueException/Discord.Net pull request #367
Opened 2016-11-20 20:30 UTC by FiniteReality

According to my testing, resolves #366, #365 as well as CommandService.Commands/Modules not returning all registered commands/modules respectively.

2016-11-25 18:15 UTC, Auralytical requested changes

2016-11-25 18:15 UTC, RogueException commented on src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs
> +                {
Style consistency: remove braces

2016-11-25 18:15 UTC, RogueException commented on src/Discord.Net.Commands/Builders/ModuleClassBuilder.cs
> +                builder.Name = method.Name;
We already have this on line 119

2016-11-25 20:04 UTC, james7132 commented
Just tested this on my current setup, and it does not resolve #365: there is still a null alias included. Will report back why as soon as possible.

2016-11-25 20:43 UTC, james7132 commented
The following code still triggers a NullReferenceException as described in #365:

```csharp
public class Admin : ModuleBase {

  [Group("prune")]
  public class Prune : ModuleBase {

    [Command]
    public Task Default(int count) {
      ...
    }

  }

}
```

The builder has a single null alias and the module has no aliases in this case.

2016-11-25 20:43 UTC, FiniteReality commented
@james7132 Interesting; it appears to be fixed for me:
![screenshot_20161125_204315](https://cloud.githubusercontent.com/assets/21000186/20635057/ce5d631c-b34f-11e6-92b4-47cfdb4e4475.png)

Mind showing your code?

2016-11-25 20:46 UTC, james7132 commented
For the exact code, check [here](https://github.com/james7132/Hourai/blob/master/src/Modules/Admin/Prune.cs#L18).

2016-11-25 20:56 UTC, james7132 commented
Yes I am currently on commit 05fb81c.

2016-11-25 20:57 UTC, FiniteReality commented
@foxbot I can reproduce the issue; my Permutate code is returning an empty result which is incorrect

2016-11-25 21:17 UTC, FiniteReality commented
Okay, it should be fixed now. I'll work on fixing the reviewed issues now.

2016-11-26 00:28 UTC, james7132 commented
Can confirm that this resolves  #365 now.

2016-11-27 03:25 UTC, Auralytical approved these changes

2016-11-27 03:27 UTC, merged