Add relationship features
RogueException/Discord.Net pull request #369
Opened 2016-11-21 17:16 UTC by ObsidianMinor

Opening this pull request for when work starts on 1.1

Adds methods to get relationships, add users as friends, block users, and remove relationship for a specified user.

2016-11-21 17:27 UTC, ObsidianMinor commented on src/Discord.Net.Core/API/DiscordRestApiClient.cs
> +        public async Task AddFriendAsync(ulong userId, RequestOptions options = null)
If the current relationship is IncomingRequest, this method accepts the request. If there is no relationship, it will send a friend request

2016-11-21 18:47 UTC, ObsidianMinor commented
When pulled, this will close #64

2017-03-07 14:17 UTC, khionu requested changes
You alternate between the noun "relations" and "relationships". "Relations" is not context-correct, I would recommend refactoring to use "relationships".

That, and the AverageRelationshipsPerUser is an optimizer, it should be a statistically-accurate number. 30 may sound reasonable (it does to me, too), but should get more data on that, if you don't have it already.

2017-03-07 14:17 UTC, khionu commented on src/Discord.Net.WebSocket/ClientState.cs
> +        private const double AverageRelationshipsPerUser = 30;
Did you get data for this?

2017-03-08 03:16 UTC, Sentinent commented
You should also initially populate relationships from the READY event.

2017-03-08 03:32 UTC, ejectedmatrix commented
You know @ObsidianMinor until they merge this pull request you can always make it a separate class or something so people like us who can't wait can use it :P if you can please do!! and also if you could make a version for 0.9.x it'd be amazing!

2017-03-08 04:11 UTC, ObsidianMinor commented
@Sentinent [I already do](https://github.com/RogueException/Discord.Net/pull/369/files#diff-714cba74b189aefe65e5bd00bde121a2R491)

2017-06-15 14:49 UTC, closed without merging