Adds Timestamps to embeds, and removes Image and Thumbnail-Builders
RogueException/Discord.Net pull request #375
Opened 2016-11-25 20:58 UTC by LassieME

Not sure about the ImageUrl and ThumbnailUrl implementation, but this works.

2016-11-26 03:37 UTC, Auralytical requested changes

2016-11-26 03:37 UTC, RogueException commented on src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
> +        public EmbedBuilder WithTimestamp()
This is unclear. should be more obvious that it's setting Timestamp to Now.
`WithNowTimestamp()` maybe? Unless someone has a better name.

2016-11-26 03:39 UTC, LassieME commented on src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
> +        public EmbedBuilder WithTimestamp()
Sounds good to me.

2016-11-26 03:41 UTC, RogueException commented on src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
> +        public EmbedBuilder WithTimestamp()
That works

2016-11-27 04:12 UTC, Auralytical approved these changes

2016-11-27 04:20 UTC, merged