Resolves #359: Combines event arguments into one struct.
RogueException/Discord.Net pull request #395
Opened 2016-12-03 16:48 UTC by LassieME

Makes #358 obsolete and should resolve #359.

Honestly not sure I like this solution using only one struct, having a check for IsDownloadable and throwing an exception for MessageDeleted seems a bit, idk, janky. 

Might make more sense to either split it up into multiple structs or take the GC penalty and make it an abstract class. That would also make it applicable to use in the PresenceUpdate event, which with this current setup is the only event that still uses Optional. Looking forward to reading your thoughts on this one.

Still left to do:
- [ ] Docstrings for events and cached struct.

2016-12-03 16:56 UTC, FiniteReality commented
I think we should make the restriction for `Cached<T>` simply be `IEntity` - that way it works for all entity types without changes in the future. Also, I don't think we need the `IsDownloadable` flag; entities which use the `Cached<T>` type should always be able to be downloaded.

2016-12-03 17:02 UTC, LassieME commented
So your suggestion is to keep the Optional on the MessageDeleted event? I guess that's OK, but it sounded like Voltana didn't like exposing Optional outside of APIClient.

2016-12-03 17:20 UTC, FiniteReality commented
Huh, good point - I forgot that message delete events don't always have the message cached.

Also, there's one issue with the `Cached<T>` type: what happens when the entity id is no longer a ulong? `Entity<TId>` supports multiple values for entity ids, so we should probably change the definition to be something like this:

```cs
public struct Cached<TEntity> where TEntity : Entity<TId>
```

That way we have `TEntity` for the entity type, and `TId` for the id type.

Furthermore, I think it would be useful to have some static helper methods to create `Cached<T>` types from an entity, and an entity id.

2016-12-03 21:41 UTC, LassieME commented
I assume you meant `IEntity<TId>`?

2016-12-04 00:48 UTC, LassieME commented
How would that work with the message deleted event? @foxbot I'm kinda blanking on how that would even work. If you could expand on your idea a little that would be great.

2016-12-16 22:52 UTC, LassieME commented
I think this is ready for review.

2016-12-20 10:37 UTC, LassieME commented
Sounds good, invite sent.

2017-02-20 22:44 UTC, Auralytical requested changes

2017-02-20 22:44 UTC, RogueException commented on src/Discord.Net.Core/Utils/Cacheable.cs
> +        public bool HasValue => !EqualityComparer<TEntity>.Default.Equals(Value, default(TEntity));
Integer == 0 does not mean it has no value. This should be a bool passed to the constructor

2017-02-20 22:45 UTC, RogueException commented
Sorry this took so long, had to figure out how this lined up with other event changes. After the one fix, LGTM.

2017-02-21 14:31 UTC, LassieME commented
Fixed.

2017-03-01 22:23 UTC, Auralytical approved these changes

2017-03-01 22:35 UTC, merged

2017-03-04 21:38 UTC, AntiTcb commented on src/Discord.Net.Core/Utils/Cacheable.cs
> +        public bool HasValue { get; }
Shouldn't this be `public bool HasValue => Value != null;`?

2017-03-04 22:05 UTC, RogueException commented on src/Discord.Net.Core/Utils/Cacheable.cs
> +        public bool HasValue { get; }
No, because null is a valid value, and there's no class constraint. We can't be sure we wont use this helper in other places, so best to be safe.

2017-03-04 22:23 UTC, AntiTcb commented on src/Discord.Net.Core/Utils/Cacheable.cs
> +        public bool HasValue { get; }
Shouldn't the value types be wrapped in a nullable anyway? Probably making a bigger deal out of this than necessary, but it seems worrying for the potential of HasValue to be false if Value actually exists.

2017-03-05 00:10 UTC, RogueException commented on src/Discord.Net.Core/Utils/Cacheable.cs
> +        public bool HasValue { get; }
Nullable still isnt a reference type.