Add embed builder extensions
RogueException/Discord.Net pull request #460
Opened 2017-01-03 23:23 UTC by FiniteReality

People in #dotnet_discord-net suggested that this should be part of the lib after I demonstrated it.

2017-01-04 00:27 UTC, khionu approved these changes
LGTM

2017-01-26 15:00 UTC, RogueException commented
Should these be extensions? Or part of the EmbedBuilder?

2017-01-26 15:03 UTC, khionu commented
Might make more sense as overloads

2017-03-15 10:35 UTC, Erlite commented
Looks good 👍

2017-03-15 10:41 UTC, RyadaProductions commented
Looking good.

2017-06-29 14:24 UTC, AntiTcb commented
Mind throwing in 
```cs
public static EmbedBuilder AddFields(this EmbedBuilder builder, IEnumerable<EmbedFieldBuilder> fields)
        {
            foreach (var field in fields)
                builder.AddField(field);

            return builder;
        }
```
really quickly?

2017-06-29 14:32 UTC, FiniteReality commented
Why would that be useful? It seems like something that would have a very specific use-case.

2017-06-29 14:40 UTC, AntiTcb commented
This is probably the one specific use case, but I ran into writing that up after opting for a `yield return` for generating fields.  It honestly doesn't add much, but, it doesn't take away anything either by including it.

2017-06-29 14:42 UTC, FiniteReality commented
If that's the only use case, you should be writing the extension yourself. There's no real point adding extension methods for one specific use case when they're not even that hard to add yourself

2017-06-29 15:00 UTC, Joe4evr commented
@AntiTcb I'm more a fan of this one, really:
```cs
public static EmbedBuilder AddFieldSequence<T>(
    this EmbedBuilder builder,
    IEnumerable<T> seq,
    Action<EmbedFieldBuilder, T> action)
{
    foreach (var item in seq)
    {
        builder.AddField(efb => action(efb, item));
    }

    return builder;
}
```

2017-06-29 20:17 UTC, RogueException commented
Do we still want sub-builders? They don't seem to really add much.

2017-06-29 20:18 UTC, Joe4evr commented
I don't think I can do `AddFieldWhen()` nicely without sub-builders, though.

2017-06-29 22:33 UTC, Auralytical requested changes

2017-06-29 22:33 UTC, RogueException commented on src/Discord.Net.Rest/Extensions/EmbedBuilderExtensions.cs
> +        public static EmbedBuilder WithColor(this EmbedBuilder builder, float r, float g, float b) =>
Needs int overload too

2017-06-29 22:44 UTC, merged