Fix detection of IDependencyMap impl
RogueException/Discord.Net pull request #546
Opened 2017-03-01 12:14 UTC by khionu

Not pretty, but it works.

2017-03-01 22:11 UTC, Auralytical requested changes

2017-03-01 22:11 UTC, RogueException commented on src/Discord.Net.Commands/Dependencies/DependencyMap.cs
> +                throw new InvalidOperationException("The dependency map cannot contain services directly added as IDependencyMap or CommandService. Only Implimentations and Derivatives are permitted"
I'd clean this up by looking for each type individually and splitting this into two exception messages.

2017-03-01 22:11 UTC, RogueException commented on src/Discord.Net.Commands/Dependencies/DependencyMap.cs
> +                throw new InvalidOperationException("The dependency map cannot contain services directly added as IDependencyMap or CommandService. Only Implimentations and Derivatives are permitted"
I'd probably just keep it simple and explain why. `IDependencyMap is used internally and cannot be added as a dependency`.

2017-03-02 06:14 UTC, khionu commented on src/Discord.Net.Commands/Dependencies/DependencyMap.cs
> +                throw new InvalidOperationException("The dependency map cannot contain services directly added as IDependencyMap or CommandService. Only Implimentations and Derivatives are permitted"
Same for CommandService?

2017-03-02 06:15 UTC, khionu commented on src/Discord.Net.Commands/Dependencies/DependencyMap.cs
> +                throw new InvalidOperationException("The dependency map cannot contain services directly added as IDependencyMap or CommandService. Only Implimentations and Derivatives are permitted"
IE, `s/IDependencyMap/CommandService/`, but same message?

2017-03-18 11:42 UTC, merged