Overloaded AddModuleAsync with Type
RogueException/Discord.Net pull request #581
Opened 2017-03-21 20:37 UTC by Bond-009

IDK

2017-03-21 20:43 UTC, MarkusGordathian commented
How is this different from `AddModule<T>()`?

2017-03-21 20:45 UTC, Bond-009 commented
You can do things like this:
```csharp
foreach (KeyValuePair<System.Type, bool> pair in dic)
{
    if (pair.Value)
    {
        await CommandService.AddModuleAsync(pair.Key);
    }
}
```

2017-03-21 20:45 UTC, FiniteReality commented
:-1: Code duplication which could have been avoided by redirecting one method to the other. Also, there is no check that the type is actually a valid module before attempting to build it.

@MarkusGordathian `AddModule(type)` is useful for when you don't have access to use its generic twin, e.g. if you're loading modules from a source other than an Assembly.

2017-03-21 20:50 UTC, Bond-009 commented
@FiniteReality better?

2017-03-21 20:51 UTC, FiniteReality commented on src/Discord.Net.Commands/CommandService.cs
> +        public async Task<ModuleInfo> AddModuleAsync<T>() => await AddModuleAsync(typeof(T));
Remove `async` and `await` here, there's no need to use an async context as we're just redirecting to the other method.

2017-03-21 20:52 UTC, Bond-009 commented on src/Discord.Net.Commands/CommandService.cs
> +        public async Task<ModuleInfo> AddModuleAsync<T>() => await AddModuleAsync(typeof(T));
Done

2017-03-21 20:54 UTC, FiniteReality commented
:+1: LGTM, with this I can add a nice check to AddModuleAsync to prevent non-module types from attempting to be added before we try to build them.

2017-03-23 14:24 UTC, Auralytical requested changes
This change should be done to RemoveModuleAsync too for consistency.

2017-03-24 17:08 UTC, FiniteReality commented on src/Discord.Net.Commands/CommandService.cs
> +        public Task<bool> RemoveModuleAsync<T>()
Use an expression-bodied method here for consistency

2017-04-29 07:42 UTC, merged