Add various property validation in EmbedBuilder
RogueException/Discord.Net pull request #711
Opened 2017-06-18 09:27 UTC by moiph

2017-06-18 09:28 UTC, moiph commented on src/Discord.Net.Rest/Entities/Messages/EmbedBuilder.cs
> +        public const int MaxFieldCount = 25;
Any preference on using DiscordConfig for these consts?

2017-06-18 09:31 UTC, moiph commented
I preferred I can update all of the getters/setters to be consistent ( get => field  vs get { return field } ), usually I prefer to keep that type of cleanup isolated from functional changes.

2017-06-18 20:25 UTC, AntiTcb commented on src/Discord.Net.Rest/Entities/Messages/EmbedBuilder.cs
>          public string Url { get { return _embed.Url; } set { _embed.Url = value; } }
I can't help but feel like these would be better as `System.Uri`s rather than strings.

2017-06-18 20:25 UTC, AntiTcb commented on src/Discord.Net.Rest/Entities/Messages/EmbedBuilder.cs
> +                if (value?.Length > MaxFieldNameLength) throw new ArgumentException($"Field name length must be less than or equal to {MaxFieldNameLength}.");
Should probably also check field names/values for empty strings or nulls since those also throw back 400s.

2017-06-18 20:26 UTC, moiph commented on src/Discord.Net.Rest/Entities/Messages/EmbedBuilder.cs
> +                if (value?.Length > MaxFieldNameLength) throw new ArgumentException($"Field name length must be less than or equal to {MaxFieldNameLength}.");
Good call, agreed

2017-06-18 20:38 UTC, FiniteReality commented on src/Discord.Net.Rest/Entities/Messages/EmbedBuilder.cs
>          public string Url { get { return _embed.Url; } set { _embed.Url = value; } }
I concur; using the Uri type means that we get validation of the input as an artefact of its implementation, and IMO the Uri class is nicer to work with.

2017-06-18 22:18 UTC, moiph commented on src/Discord.Net.Rest/Entities/Messages/EmbedBuilder.cs
>          public string Url { get { return _embed.Url; } set { _embed.Url = value; } }
Agreed I'm a fan of that change. So much for a single file edit :)

2017-06-18 22:19 UTC, moiph commented
Regarding the overall character limit -- it seems 4000 is not accurate.  So I'm intentionally excluding that for now until we can get a clearer idea of what those limits are.

2017-06-19 13:21 UTC, FiniteReality approved these changes

2017-06-19 13:24 UTC, FiniteReality requested changes
The ArgumentException instances should be passed the property name too, I missed this initially.

2017-06-20 10:41 UTC, FiniteReality approved these changes

2017-06-22 05:21 UTC, moiph commented on src/Discord.Net.Core/Entities/Messages/Embed.cs
> +        public int Length => Title?.Length + Author?.Name?.Length + Description?.Length + Footer?.Text?.Length + Fields.Sum(f => f.Name.Length + f.Value.ToString().Length) ?? 0;
This assumes only text properties count toward the limit; if URLs count then obviously this needs an update :)

2017-06-23 14:29 UTC, merged