Proposed Solution for #674 Permissions Changes
RogueException/Discord.Net pull request #743
Opened 2017-07-08 08:12 UTC by Chris-Johnston

Changed the ChannelPermission, GuildPermission enums to match the Discord API. Adjusted relevant methods to match this change. Also added view audit logs permission to guild permission while I was at it.

Will using System.Math.Pow cause compatibility issues? (had to import System)

This is a breaking change, both the values and names of the enum definition have been modified.

2017-07-08 08:28 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Permissions/ChannelPermission.cs
> +    public enum ChannelPermission : ulong
Is `[FlagsAttribute]` what you were looking for? https://msdn.microsoft.com/en-us/library/system.flagsattribute(v=vs.110).aspx

2017-07-08 08:28 UTC, Joe4evr commented on src/Discord.Net.Core/Entities/Permissions/ChannelPermission.cs
> +        CREATE_INSTANT_INVITE =     0x00000001,
Also, the comments categorizing each section of permissions would be nice to still have in source. And maybe put an `_` every two digits for readability.

2017-07-08 08:31 UTC, Joe4evr commented
You updated just before I commented.
> Also, the comments categorizing each section of permissions would be nice to still have in source. And maybe put an _ every two digits for readability.

2017-07-08 08:39 UTC, Chris-Johnston commented
Added @Joe4evr suggested changes

2017-07-08 08:40 UTC, Chris-Johnston commented
Added @foxbot 's suggested changes

2017-07-08 08:55 UTC, SubZero0 commented on src/Discord.Net.Core/Entities/Permissions/ChannelPermissions.cs
> +        public bool ManagePermissions => Permissions.GetValue(RawValue, ChannelPermission.ManageRoles);
Should probably change "ManagePermissions" to "ManageRoles"

2017-07-08 08:55 UTC, SubZero0 commented on src/Discord.Net.Core/Entities/Permissions/OverwritePermissions.cs
> +        public PermValue ManagePermissions => Permissions.GetValue(AllowValue, DenyValue, ChannelPermission.ManageRoles);
See above

2017-07-08 09:05 UTC, Chris-Johnston commented on src/Discord.Net.Core/Entities/Permissions/ChannelPermissions.cs
> +        public bool ManagePermissions => Permissions.GetValue(RawValue, ChannelPermission.ManageRoles);
Added in 236775c2d8aca9481d6c51c674f5727f97adec04 and 9f1c6d0f425bc93b153f32f6e5b147f79d772499

2017-07-08 13:59 UTC, FiniteReality requested changes
Looks fairly good, though I think we could do some more clean up afterwards

2017-07-08 13:59 UTC, FiniteReality commented on src/Discord.Net.Core/Entities/Permissions/ChannelPermissions.cs
> +                ulong flag = (ulong)Math.Pow(2, i);
Use `1<<i` here rather than Math.Pow

2017-07-08 13:59 UTC, FiniteReality commented on src/Discord.Net.Core/Entities/Permissions/GuildPermissions.cs
> +                ulong flag = (ulong)Math.Pow(2, i);
Likewise, `1<<i` rather than Math.Pow

2017-07-08 13:59 UTC, FiniteReality commented on src/Discord.Net.Core/Entities/Permissions/OverwritePermissions.cs
> +                ulong flag = (ulong)Math.Pow(2, i);
`1<<i`

2017-07-08 13:59 UTC, FiniteReality commented on src/Discord.Net.Core/Entities/Permissions/OverwritePermissions.cs
> +                ulong flag = (ulong)Math.Pow(2, i);
`1<<i`

2017-07-08 16:51 UTC, Chris-Johnston commented
Added @FiniteReality 's requested changes

2017-10-19 05:18 UTC, Chris-Johnston commented
Formatted the two enums so that they are displayed in neat columns in the source.

Also, could we add the `Hacktoberfest` label to this PR?

2017-10-19 17:14 UTC, FiniteReality commented
I think hacktoberfest labels only apply to issues: PRs are automagically counted.

2017-10-20 09:16 UTC, FiniteReality approved these changes

2017-10-26 00:39 UTC, merged